### ISSUE TITLE
Firefox shows Connection not secure

### ISSUE THREAD

**Issue by Parth-Vader** [SebastinSanty/PersonalWebsite#1]
![screenshot from 2016-09-24 21-02-30](https://cloud.githubusercontent.com/assets/16269320/18809497/c2b155ae-829a-11e6-878e-49389f097bb4.png)

**Comment by SebastinSanty** [comment]
It is http://sebastinsanty.com, so no need of security. Why did you open in https?

**Comment by Parth-Vader** [comment]
It's in your description. I clicked on it.

**Comment by SebastinSanty** [comment]
Which description?

**Comment by Parth-Vader** [comment]
![screenshot from 2016-09-24 21-13-38](https://cloud.githubusercontent.com/assets/16269320/18809537/b4771626-829b-11e6-8cb3-921b2ab43161.png)

**Comment by SebastinSanty** [comment]
Thanks Parth for pointing that out ;)
